### ISSUE TITLE
Babel.localeselector missing in flask-babel 3.0.0

### ISSUE THREAD

**Issue by AiyionPrime** [lemoer/keepitup#17]
> - Babel.locale_selector and Babel.timezone_selector no longer exist. They must be provided
>   either when the Babel() object is created or when init_app() is called. This is to support
>   having a single Babel object for multiple Flask apps (#107) as well as to simplify settings
>   and multi-threaded state.

_https://github.com/python-babel/flask-babel/blob/master/CHANGELOG Section 3.0.0_

One option would be to temporarily pin flask-babel to `2.0.0` as well.

@moridius started working on a proper fix, which gets rid of the decorator.

**Comment by AiyionPrime** [comment]
@moridius I gave you write access on my fork, feel free to use it for PRs.
Reading the above doc, I think it should be possible to get rid of the `init_app`-line and put the locale selector in line 15 instead.

**Comment by lemoer** [comment]
Fixed in the main branch.
