### ISSUE TITLE
Translate to german

### ISSUE THREAD

**Issue by moridius** [lemoer/keepitup#6]
As Hannover is in Germany we should translate the tool to german in order to keep it simple for the majority of users. This was already suggested in https://github.com/lemoer/keepitup/issues/1.

I would suggest two steps:

1. Translate everything to german (hardcoded) as a quick solution.
2. Check out Flask-Babel or similar and see whether we can provide a german and an english version.

I will send a PR for step 1 if desired.

**Comment by lemoer** [comment]
I would suggest trying out Flask-Babel. I have found a tutorial [here](https://medium.datadriveninvestor.com/translating-your-web-app-via-flask-babel-a1561376256c). Doesn't seem so much hassle.
